# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 5.5
install:
  - composer install

# omitting "script:" will default to phpunit
script: phpunit --configuration tax/Tests/phpunit.xml

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "ovidiumght@gmail.com"